import { X, ShieldCheck } from "lucide-react";

// ── PRIVACY POLICY MODAL ──
// Reusable popup. Renders on top of the signup form, no page reload/navigation.
// Usage: <PrivacyPolicyModal open={showPrivacyModal} onClose={() => setShowPrivacyModal(false)} />
export default function PrivacyPolicyModal({ open, onClose }) {
  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-[999] bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        className="bg-white w-full max-w-2xl max-h-[85vh] rounded-[2rem] shadow-2xl border border-white/50 flex flex-col overflow-hidden animate-in zoom-in-95 slide-in-from-bottom-4 duration-300"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-slate-100 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="bg-blue-100 p-2.5 rounded-xl text-blue-600">
              <ShieldCheck className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-lg font-black text-slate-900">Privacy Policy & Terms</h2>
              <p className="text-xs font-bold text-slate-400">NeuroGuard AI — Last updated: 2026</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl hover:bg-slate-100 text-slate-400 hover:text-slate-700 transition-all"
            aria-label="Close"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Scrollable body */}
        <div className="overflow-y-auto p-8 space-y-6 text-sm text-slate-700 leading-relaxed custom-scrollbar">
          <section>
            <h3 className="font-black text-slate-900 mb-2">1. Introduction</h3>
            <p>
              NeuroGuard AI ("we", "our", "the platform") provides AI-assisted screening for
              Motor Neuron Disease (MND) patterns based on nerve conduction and EMG reports you
              upload. This policy explains what data we collect, how we use it, and your rights.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 mb-2">2. What We Collect</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Account info: name, email, password (encrypted), role, age, gender</li>
              <li>Medical reports you upload (images or JSON files) and data extracted from them</li>
              <li>Screening results generated by our AI/ML model</li>
              <li>Basic usage logs (login times, requests made to our system)</li>
            </ul>
          </section>

          <section>
            <h3 className="font-black text-slate-900 mb-2">3. How We Use Your Data</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>To generate your AI-based screening result and body-region mapping</li>
              <li>To connect you with relevant doctors, only if you choose to connect</li>
              <li>To improve the accuracy of our screening model, in aggregated/anonymized form only</li>
            </ul>
          </section>

          <section>
            <h3 className="font-black text-slate-900 mb-2">4. Third-Party Processing</h3>
            <p>
              Uploaded report images are processed using Google's Gemini AI API to extract clinical
              data. This means report images are transmitted to Google's servers for OCR/analysis.
              We do not sell or share your data with advertisers or unrelated third parties.
            </p>
          </section>

          <section className="bg-amber-50 border border-amber-200 rounded-2xl p-4">
            <h3 className="font-black text-amber-900 mb-2">5. Medical Disclaimer</h3>
            <p className="text-amber-900">
              NeuroGuard AI is a screening aid, not a diagnostic tool. Results shown do not
              constitute a medical diagnosis. Always consult a licensed neurologist or physician
              for confirmation and treatment decisions.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 mb-2">6. Data Storage & Security</h3>
            <p>
              Your data is stored in our secure database. Passwords are hashed and never stored in
              plain text. We take reasonable technical measures to protect your data, but no system
              is 100% secure, and we cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 mb-2">7. Your Rights</h3>
            <p>
              You may request access to, correction of, or deletion of your personal data by
              contacting platform support. You may discontinue use of the platform at any time.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 mb-2">8. Doctor Access</h3>
            <p>
              If you choose to connect with a doctor through the platform, that doctor will be able
              to view your uploaded report and screening results for the purpose of clinical
              consultation.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 mb-2">9. Changes to This Policy</h3>
            <p>
              We may update this policy from time to time. Continued use of the platform after
              changes constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 mb-2">10. Contact</h3>
            <p>For privacy-related questions, contact: support@neuroguard.ai</p>
          </section>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-slate-100 flex-shrink-0">
          <button
            onClick={onClose}
            className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-bold py-3.5 rounded-xl shadow-lg active:scale-95 transition-all"
          >
            Got it
          </button>
        </div>
      </div>
    </div>
  );
}
